
services:
  r-0.49:
    image: "rhub/evercran-build:0.49"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: 0.49
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.50-a1:
    image: "rhub/evercran-build:0.50-a1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: 0.50-a1
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.50-a4:
    image: "rhub/evercran-build:0.50-a4"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: 0.50-a4
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.60:
    image: "rhub/evercran-build:0.60"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.60"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.60.1:
    image: "rhub/evercran-build:0.60.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.60.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61:
    image: "rhub/evercran-build:0.61"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61.1:
    image: "rhub/evercran-build:0.61.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61.2:
    image: "rhub/evercran-build:0.61.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61.3:
    image: "rhub/evercran-build:0.61.3"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61.3"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62:
    image: "rhub/evercran-build:0.62"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.1:
    image: "rhub/evercran-build:0.62.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.2:
    image: "rhub/evercran-build:0.62.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.3:
    image: "rhub/evercran-build:0.62.3"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.3"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.4:
    image: "rhub/evercran-build:0.62.4"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.4"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63:
    image: "rhub/evercran-build:0.63"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63.1:
    image: "rhub/evercran-build:0.63.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63.2:
    image: "rhub/evercran-build:0.63.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63.3:
    image: "rhub/evercran-build:0.63.3"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63.3"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.64.0:
    image: "rhub/evercran-build:0.64.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.64.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.64.1:
    image: "rhub/evercran-build:0.64.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.64.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.64.2:
    image: "rhub/evercran-build:0.64.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.64.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.65.0:
    image: "rhub/evercran-build:0.65.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.65.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.65.1:
    image: "rhub/evercran-build:0.65.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.65.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.65.2:
    image: "rhub/evercran-build:0.65.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.65.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.90.0:
    image: "rhub/evercran-build:0.90.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.90.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.90.1:
    image: "rhub/evercran-build:0.90.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.90.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.99.0:
    image: "rhub/evercran-build:0.99.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.99.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.0.0:
    image: "rhub/evercran-build:1.0.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.0.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output
