
services:
  r-0.49:
    image: "rhub/evercran-build:0.49"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: 0.49
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.50-a1:
    image: "rhub/evercran-build:0.50-a1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: 0.50-a1
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.50-a4:
    image: "rhub/evercran-build:0.50-a4"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: 0.50-a4
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.60:
    image: "rhub/evercran-build:0.60"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.60"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.60.1:
    image: "rhub/evercran-build:0.60.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.60.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61:
    image: "rhub/evercran-build:0.61"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61.1:
    image: "rhub/evercran-build:0.61.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61.2:
    image: "rhub/evercran-build:0.61.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.61.3:
    image: "rhub/evercran-build:0.61.3"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.61.3"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62:
    image: "rhub/evercran-build:0.62"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.1:
    image: "rhub/evercran-build:0.62.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.2:
    image: "rhub/evercran-build:0.62.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.3:
    image: "rhub/evercran-build:0.62.3"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.3"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.62.4:
    image: "rhub/evercran-build:0.62.4"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.62.4"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63:
    image: "rhub/evercran-build:0.63"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63.1:
    image: "rhub/evercran-build:0.63.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63.2:
    image: "rhub/evercran-build:0.63.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.63.3:
    image: "rhub/evercran-build:0.63.3"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.63.3"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.64.0:
    image: "rhub/evercran-build:0.64.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.64.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.64.1:
    image: "rhub/evercran-build:0.64.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.64.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.64.2:
    image: "rhub/evercran-build:0.64.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.64.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.65.0:
    image: "rhub/evercran-build:0.65.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.65.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.65.1:
    image: "rhub/evercran-build:0.65.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.65.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.65.2:
    image: "rhub/evercran-build:0.65.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.65.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.90.0:
    image: "rhub/evercran-build:0.90.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.90.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.90.1:
    image: "rhub/evercran-build:0.90.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.90.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-0.99.0:
    image: "rhub/evercran-build:0.99.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "0.99.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.0.0:
    image: "rhub/evercran-build:1.0.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.0.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.0.1:
    image: "rhub/evercran-build:1.0.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.0.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.1.0:
    image: "rhub/evercran-build:1.1.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.1.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.1.1:
    image: "rhub/evercran-build:1.1.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.1.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.2.0:
    image: "rhub/evercran-build:1.2.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.2.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.2.1:
    image: "rhub/evercran-build:1.2.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.2.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.2.2:
    image: "rhub/evercran-build:1.2.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.2.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.2.3:
    image: "rhub/evercran-build:1.2.3"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.2.3"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.3.0:
    image: "rhub/evercran-build:1.3.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.3.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.3.1:
    image: "rhub/evercran-build:1.3.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.3.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.4.0:
    image: "rhub/evercran-build:1.4.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.4.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.4.1:
    image: "rhub/evercran-build:1.4.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.4.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.5.0:
    image: "rhub/evercran-build:1.5.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.5.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.5.1:
    image: "rhub/evercran-build:1.5.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.5.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.6.0:
    image: "rhub/evercran-build:1.6.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.6.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.6.1:
    image: "rhub/evercran-build:1.6.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.6.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.6.2:
    image: "rhub/evercran-build:1.6.2"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.6.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.7.0:
    image: "rhub/evercran-build:1.7.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.7.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.7.1:
    image: "rhub/evercran-build:1.7.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.7.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.8.0:
    image: "rhub/evercran-build:1.8.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.8.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.8.1:
    image: "rhub/evercran-build:1.8.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.8.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.9.0:
    image: "rhub/evercran-build:1.9.0"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.9.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-1.9.1:
    image: "rhub/evercran-build:1.9.1"
    build:
      context: .
      dockerfile: Dockerfile-sarge
      args:
        R_VERSION: "1.9.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.0.0:
    image: "rhub/evercran-build:2.0.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.0.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.0.1:
    image: "rhub/evercran-build:2.0.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.0.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.1.0:
    image: "rhub/evercran-build:2.1.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.1.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.1.1:
    image: "rhub/evercran-build:2.1.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.1.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.2.0:
    image: "rhub/evercran-build:2.2.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.2.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.2.1:
    image: "rhub/evercran-build:2.2.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.2.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.3.0:
    image: "rhub/evercran-build:2.3.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.3.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.3.1:
    image: "rhub/evercran-build:2.3.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.3.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.4.0:
    image: "rhub/evercran-build:2.4.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.4.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.4.1:
    image: "rhub/evercran-build:2.4.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.4.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.5.0:
    image: "rhub/evercran-build:2.5.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.5.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.5.1:
    image: "rhub/evercran-build:2.5.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.5.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.6.0:
    image: "rhub/evercran-build:2.6.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.6.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.6.1:
    image: "rhub/evercran-build:2.6.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.6.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.6.2:
    image: "rhub/evercran-build:2.6.2"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.6.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.7.0:
    image: "rhub/evercran-build:2.7.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.7.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.7.1:
    image: "rhub/evercran-build:2.7.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.7.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.7.2:
    image: "rhub/evercran-build:2.7.2"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.7.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.8.0:
    image: "rhub/evercran-build:2.8.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.8.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.8.1:
    image: "rhub/evercran-build:2.8.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.8.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.9.0:
    image: "rhub/evercran-build:2.9.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.9.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.9.1:
    image: "rhub/evercran-build:2.9.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.9.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.9.2:
    image: "rhub/evercran-build:2.9.2"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.9.2"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.10.0:
    image: "rhub/evercran-build:2.10.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.10.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.10.1:
    image: "rhub/evercran-build:2.10.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.10.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.11.0:
    image: "rhub/evercran-build:2.11.0"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.11.0"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output

  r-2.11.1:
    image: "rhub/evercran-build:2.11.1"
    build:
      context: .
      dockerfile: Dockerfile-wheezy
      platforms:
        - "linux/i386"
      args:
        R_VERSION: "2.11.1"
    command: bash -c 'cp /build/*.deb /output'
    volumes:
      - ./output:/output
